import { Song } from "../../types/songs";

export const justDance: Song = {
  title: "Just Dance",
  slug: "just-dance",
  artist: "Lady Gaga",
  year: "2008",
  studio: "Record Plant Studios",
  location: "Los Angeles, CA",
  bpm: 119,
  start: 4,
  end: 248,
  tracks: [
    {
      id: crypto.randomUUID(),
      name: "Kick",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/kickdrum.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Snare",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/snare.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Cymbals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/cymbals.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Synth 1",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/synth1.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Synth 2",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/synth2.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Extra Synth",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/extrasynth.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Vocals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/vocals.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
  ],
  buses: [
    {
      id: crypto.randomUUID(),
      name: "Bus 1",
      volume: 0.61,
      fxName: ["nofx", "nofx"],
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
    },
    {
      id: crypto.randomUUID(),
      name: "Bus 2",
      volume: 0.61,
      fxName: ["nofx", "nofx"],
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
    },
  ],
};
