import { Song } from "../../types/songs";

export const blueMonday: Song = {
  title: "Blue Monday",
  slug: "blue-monday",
  artist: "New Order",
  year: "1986",
  studio: "Britannia Row Studios",
  location: "London, England",
  bpm: 139,
  start: 0,
  end: 490,
  tracks: [
    {
      id: crypto.randomUUID(),
      name: "Drums 1",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/01-Drums-01.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Drums 2",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/02-Drums-02.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Drums 3",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/03-Drums-03.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "SynthBass",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/04-Synth-Bass.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Bass Gtr",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/05-Real-Bass.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Synths 1",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/07-Synths-01.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Synths 2",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/08-Synths-02.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Vocals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/blueMonday/06-Vocals.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
    },
  ],
  buses: [
    {
      id: crypto.randomUUID(),
      name: "Bus 1",
      volume: 0.61,
      fxName: ["nofx", "nofx"],
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
    },
    {
      id: crypto.randomUUID(),
      name: "Bus 2",
      volume: 0.61,
      fxName: ["nofx", "nofx"],
      reverbMix: [0.5, 0.5],
      reverbPreDelay: [0.5, 0.5],
      reverbDecay: [0.5, 0.5],
      reverbBypass: [false, false],
      delayMix: [0.5, 0.5],
      delayTime: [1, 1],
      delayFeedback: [0.5, 0.5],
      delayBypass: [false, false],
      pitchShiftBypass: [false, false],
      pitchShiftMix: [0.5, 0.5],
      pitchShiftPitch: [5, 5],
      panelPosition: { x: 0, y: 0 },
      panelSize: { width: "325px", height: "auto" },
    },
  ],
};
